// Development-only check. Uses an existing Playwright install; not required by the app.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
(async()=>{
  const browser = await chromium.launch({channel:'chrome',headless:true});
  const page = await browser.newPage({viewport:{width:1500,height:1050}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.CLEANER_URL || 'http://127.0.0.1:8766');
  await page.waitForFunction(()=>document.getElementById('scanState').textContent.includes('完成'));
  await page.locator('#rows .title').first().waitFor();
  const mainCount=await page.locator('#rows tr').count();
  await page.locator('#rows .title').first().click();
  await page.waitForFunction(()=>!document.getElementById('previewMeta').textContent.includes('正在'));
  await page.screenshot({path:'.investigation/browser-main.png',fullPage:true});
  await page.locator('#rows input').first().check();
  await page.locator('#plan').click();
  await page.locator('#planDialog').waitFor({state:'visible'});
  if(await page.locator('#execute').isDisabled())throw Error('Unoccupied historical thread should be allowed while Codex runs');
  await page.locator('#closePlan').click();
  await page.locator('#rows input').first().uncheck();
  const live = await (await page.request.get(new URL('/api/state',page.url()).href)).json();
  const protectedRow = live.rows.find(r=>r.kind==='main' && r.state.includes('当前会话'));
  if(!protectedRow)throw Error('Current thread protection missing');
  await page.locator('#search').fill(protectedRow.id);
  await page.locator('#rows input').first().check();
  await page.locator('#plan').click();
  await page.locator('#planDialog').waitFor({state:'visible'});
  if(!await page.locator('#execute').isDisabled())throw Error('Current thread delete must be blocked');
  const blockers=await page.locator('#planBody .warning').allTextContents();
  await page.screenshot({path:'.investigation/browser-plan.png',fullPage:true});
  await page.locator('#closePlan').click();
  await page.locator('#search').fill('does-not-exist-1234567890');
  if(!await page.locator('#empty').isVisible())throw Error('Empty state missing');
  await page.locator('#search').fill('');
  await page.locator('#sort').selectOption('updated_at');
  await page.locator('#internalTab').click();
  const internalCount=await page.locator('#rows tr').count();
  await page.locator('#settings').click();
  await page.locator('#settingsDialog').waitFor({state:'visible'});
  await page.locator('#closeSettings').click();
  await page.locator('#mainTab').click();
  if(await page.locator('#rows').getByText('活动未知',{exact:false}).count())throw Error('Repeated unknown activity labels');
  // Only mocked routes may receive an execution request in this check.
  let submitted=[];
  await page.route('**/api/plan',route=>route.fulfill({json:{token:'mock-plan',allowed:true,bytes:2048,blockers:[],entries:[{id:'mock-a',title:'模拟会话 A',files:[],bytes:1024,blockers:[]},{id:'mock-b',title:'模拟会话 B',files:[],bytes:1024,blockers:[]}]}}));
  await page.route('**/api/delete',route=>{submitted.push(route.request().postDataJSON());return route.fulfill({json:{note:'模拟执行完成',results:[]}});});
  await page.locator('#plan').click();
  await page.getByRole('button',{name:'永久删除 2 个会话',exact:true}).waitFor({state:'visible'});
  if(await page.locator('#planDialog input').count())throw Error('Typing confirmation still present');
  if(await page.locator('#execute').isDisabled())throw Error('Allowed batch needs extra confirmation');
  await page.getByRole('button',{name:'永久删除 2 个会话',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('result').textContent.includes('模拟执行完成'));
  if(submitted.length!==1||submitted[0].confirmed!==true||submitted[0].token!=='mock-plan')throw Error('Batch confirmation payload incorrect');
  await page.locator('#closePlan').click();
  // Controlled malicious content verifies DOM handling in a real renderer.
  await page.route('**/api/preview?**',route=>route.fulfill({json:{messages:[{label:'用户',text:'<img src=x onerror="window.__xss=1"><script>window.__xss=2</script>',role:'user'}],files:[],next:null,note:'XSS fixture'}}));
  await page.locator('#rows .title').first().click();
  await page.waitForFunction(()=>document.getElementById('previewMeta').textContent==='XSS fixture');
  if(await page.locator('#messages img,#messages script').count())throw Error('HTML was interpreted');
  if(await page.evaluate(()=>window.__xss))throw Error('XSS executed');
  if(errors.length)throw Error(errors.join('\n'));
  fs.writeFileSync('.investigation/browser-results.json',JSON.stringify({mainCount,internalCount,blockers,errors,xss:'literal text only',checks:['list','preview','selection','delete blocked','empty search','sort','internal view','settings','XSS']},null,2));
  console.log(JSON.stringify({mainCount,internalCount,blockers,errors,onlineIdleAllowed:true,currentThreadBlocked:true}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
