const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1500,height:950}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const row={id:'fixture-session',title:'设置与诊断',kind:'main',project:'中文项目',cwd:'D:\\中文项目',size:1024,reclaimable:1024,updated_at:1720000000,issues:['文件缺失：D:\\中文项目\\会话.jsonl'],missing_files:['D:\\中文项目\\会话.jsonl'],file_count:0,activity:{code:'idle'},state:'普通'};await p.route('**/api/state',r=>r.fulfill({json:{csrf:'test',rows:[row],spawn_edges:{},complete:true,generation:1,status:'扫描完成 · 1 个文件',source:'元信息只读 · 会话写入锁实时检测（约每 6 秒更新）',cli:{available:true,message:'',version:'fixture',path:'C:\\codex.exe'},diagnostics:[],diagnostic_count:0,home:'D:\\中文项目'}}));await p.route('**/api/scan',r=>r.fulfill({json:{ok:true}}));await p.route('**/api/delete-progress',r=>r.fulfill({json:{running:false}}));await p.route('**/api/preview?*',r=>r.fulfill({json:{messages:[{label:'用户',text:'设置与诊断\nD:\\中文项目\\文件.txt'}],note:'分页预览：仅显示用户输入与已确认的最终回复。每页最多检查 40 条，超大消息显示占位。',files:[],next:null}}));await p.route('**/api/plan',r=>r.fulfill({json:{token:'fake',allowed:true,entries:[{id:row.id,title:row.title,files:[],bytes:1024,warnings:['文件已缺失，仅清理残留记录；缺失文件不计入释放空间：D:\\中文项目\\会话.jsonl'],blockers:[]}],blockers:[],bytes:1024}}));await p.goto('http://127.0.0.1:8766');await p.evaluate(()=>I18N.ready);await p.locator('.session-row').waitFor();await p.locator('.session-row input').check();await p.locator('.session-row .title').click();await p.locator('.message').waitFor();await p.locator('#language').selectOption('en');if(await p.locator('#settings').textContent()!=='Settings & diagnostics')throw Error('Static label');if(await p.locator('.title').first().textContent()!==row.title)throw Error('User title translated');if(!(await p.locator('.message pre').textContent()).includes('设置与诊断'))throw Error('Message translated');if(!await p.locator('.session-row input').isChecked())throw Error('Selection lost');if(await p.locator('.message b').textContent()!=='User')throw Error('Message label');await p.locator('#plan').click();await p.locator('#planDialog').waitFor({state:'visible'});if(!(await p.locator('#planDialog').innerText()).includes('Permanently delete 1 session'))throw Error('Plan translation');await p.screenshot({path:'.investigation/i18n-plan-en.png'});await p.locator('#closePlan').click();await p.locator('#settings').click();if((await p.locator('#settingsDialog').innerText()).includes('元信息只读'))throw Error('Settings translation');await p.locator('#closeSettings').click();await p.reload();await p.evaluate(()=>I18N.ready);if(await p.locator('#language').inputValue()!=='en')throw Error('Preference lost');await p.locator('#language').selectOption('zh-CN');if(await p.locator('#settings').textContent()!=='设置与诊断')throw Error('Switch back');await p.evaluate(()=>{
 completionHandled=false;selected.add('fixture-session');$('planDialog').showModal();
 finishDelete({note:'删除已结束',results:[{id:'fixture-session',title:'设置与诊断',status:'失败',message:'此 CLI 版本的会话锁协议尚未验证，禁止删除该目标'}]});
 I18N.setLanguage('en');
});
if(!(await p.locator('#result').innerText()).includes('locking protocol'))throw Error('Error translation');
if(!(await p.locator('#result').innerText()).includes('设置与诊断'))throw Error('Result title changed');
await p.evaluate(()=>I18N.setLanguage('zh-CN'));
if(!(await p.locator('#result').innerText()).includes('会话锁协议'))throw Error('Result lost on language switch');
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: English/Chinese, preference, selection, preview preservation and dialogs');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
